import { jsNft,
  ladder,
  race,
  nature,
  systemDown,
  tree,
  mern,
  temple,
  heidi,
  football } from '../assets';

export const videoDetails = [
  {
    id: 1,
    title: 'HIGHLIGHTS: Liverpool Legends 2-0 Celtic | Gerrard scores in Anfield win for LFC Foundation',
    date: '2 weeks ',
    accountName: 'Football world',
    views: '567k',
    image: football,
  },
  {
    id: 2,
    title: 'Making A Smart 2in1 Iron Ladder Is Extremely Easy And Convenient',
    date: '1 month',
    accountName: 'Creative Workers',
    views: '177k',
    image: ladder,
  },
  {
    id: 3,
    title: 'Build and Deploy Your First Modern React Native App | NFT Marketplace Course - Extremely Easy!',
    date: '6 months',
    accountName: 'JavaScript Mastery',
    views: '413k',
    image: jsNft,
  },
  {
    id: 4,
    title: '2022 Michelin GT Challenge at VIR',
    date: '5 months',
    accountName: 'Racing world',
    views: '567k',
    image: race,
  },
  {
    id: 5,
    title: '2022 Michelin GT Challenge at VIR',
    date: '1 year',
    accountName: 'MERN Tech',
    views: '1M',
    image: mern,
  },
  {
    id: 6,
    title: 'System Of A Down - B.Y.O.B. (Official HD Video)',
    date: '9 years',
    accountName: 'System Of Down',
    views: '105M',
    image: systemDown,
  },
  {
    id: 7,
    title: 'Explore the beauty of nature to make yourself relax',
    date: '2 weeks ',
    accountName: 'Nature world',
    views: '64k',
    image: nature,
  },
  {
    id: 8,
    title: 'Do you want to practice tree climbing than You must watch this',
    date: '5 years',
    accountName: 'Tree Climber',
    views: '567k',
    image: tree,
  },
  {
    id: 9,
    title: 'The Beautiful Heidi Village',
    date: '2 weeks ',
    accountName: 'Heidi',
    views: '1m',
    image: heidi,
  },
  {
    id: 10,
    title: 'Rainbow-Temple of the king (lyrics)',
    date: '1 year',
    accountName: 'Temple Heritage',
    views: '267k',
    image: temple,
  },
];
